### ISSUE TITLE
CI Compile errors on Windows

### ISSUE THREAD

**Issue by ClausKlein** [RemedyIT/axcioma#154]
**Product**
AXCIOMA

**Version**
Your HEAD version

**Describe the bug**
CI Compile errors on Windows

**To Reproduce**
[Information about how to reproduce the issue
](https://github.com/ClausKlein/axcioma/actions/runs/6449885246/workflow)

**Expected behaviour**
No Errors while CI build

**Output**
```
         D:\a\axcioma\axcioma\taox11\tao\x11\Policy_ForwardC.h(407,1): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' (compiling source file policyfactory_manager_adapter.cpp) [D:\a\axcioma\axcioma\taox11\tao\x11\taox11.vcxproj]
BRIX11 - WARNING : vs2019#build failed with exitcode 1
BRIX11 - ERROR : Executing make failed.
```

**Environment:**
Output of `ruby -v && bin/brix11 env && bin/brix11 -- configure --print-config`

**Additional context**

**Comment by jwillemsen** [comment]
Visual Studio 2019 isn't a supported/maintained platform due to lack of funding to support that compiler. The open source version of AXCIOMA has never formally supported Visual Studio 2019

**Comment by ClausKlein** [comment]
**IMHO**: We should use as default `std=c++17` for `ACE/TAO`, and `TAOX11` on all platforms.

**Comment by jwillemsen** [comment]
See https://github.com/RemedyIT/taox11/issues/273 for the upgrade to C++17

**Comment by jwillemsen** [comment]
Windows CI has been disabled, has never been formally supported, due for removal

**Comment by jwillemsen** [comment]
Closing, windows isn't supported, CI has been disabled
